### ISSUE TITLE
Mac Electron gulp start error

### ISSUE THREAD

**Issue by amakely-da** [Gravit-io/gravit-designer-plugin-starter#9]
I ran npm install on my Mac, then tried to run gulp start.  Electron threw this error:

`
[2020-05-27T15:13:23.233Z] [electron-connect] [server] started electron process: 81589
[2020-05-27T15:13:23.234Z] [electron-connect] [server] server created and listening on 30080
App threw an error during load
/Users/amakely/gravit-designer-plugin-starter-master/node_modules/gravit-designer/node_modules/electron-updater/out/AppUpdater.js:328
      }, this, { ...runtimeOptions,
                 ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at _AppUpdater (/Users/amakely/gravit-designer-plugin-starter-master/node_modules/gravit-designer/node_modules/electron-updater/out/MacUpdater.js:41:16)
`

**Comment by edge0703** [comment]
Christian here, product manager of Gravit Designer. I’m sorry, this plugin environment isn’t maintained by the Gravit Designer team anymore.

**Comment by amakely-da** [comment]
Ok.

I was looking at it because I wanted a way to assign CSS classes to
elements, so the classes would be included in the exported SVG code.

Is that feature on the Gravit roadmap?  I think Gravit is the best tool for
SVG right now, but it needs more data and bug fixes in the export.


— Andy
